services:

  carnival:
    container_name: carnival
    build: 
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - localstack
      - postgres
    environment:
      - SERVICE_NAME=carnival
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-central-1
      - S3_BUCKET_NAME=dev
      - LOCALSTACK_HOSTNAME=localstack
      - LOG_LEVEL=INFO
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_SSLMODE=disable
    volumes:
      - ./src:/app/src
    tty: true
    ports:
      - "8080:8080"
    networks:
      - carnival

  flyway:
    image: flyway/flyway
    command: migrate -url=jdbc:postgresql://postgres:5432/db -user=user -password=password -connectRetries=30
    volumes:
      - ./src/db/migration:/flyway/sql
    depends_on:
      - postgres
    tty: true
    networks:
      - carnival

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    networks:
      - carnival

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - carnival

networks:
  carnival:
    driver: bridge